version: "3.8"

include:
  - profiles_db/profiles_db.yml
  - kafka-cluster.yml

networks:
  profiles_service_network:
    name: "profiles_service_network"
    driver: bridge

services:
  profiles_service:
    build:
      dockerfile: ./alpine.Dockerfile
    command: ./bin/app
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/containers-configs/config.yml:/configs/config.yml
    ports:
      - 9080:8080
    networks:
      - profiles_service_network
      - profiles_db_network
      - kafka_network
    depends_on:
      profiles_pool:
        condition: service_started
      kafka:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "profiles_service"
      org.label-schema.group: "monitoring"
